import type { Parameter } from '~/composables/core/types'

export const fixedParentParameters: Parameter[] = [
  {
    id: 'fp1',
    name: 'Category',
    field: 'category',
    visible: true,
    header: 'Category',
    category: 'Classification',
    type: 'string',
    removable: false,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp2',
    name: 'ID',
    field: 'id',
    visible: true,
    header: 'ID',
    category: 'Classification',
    type: 'string',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp3',
    name: 'Mark',
    field: 'mark',
    visible: true,
    header: 'Mark',
    category: 'Classification',
    type: 'string',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp4',
    name: 'Host',
    field: 'host',
    visible: true,
    header: 'Host',
    category: 'Classification',
    type: 'string',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp5',
    name: 'Comment',
    field: 'comment',
    visible: true,
    header: 'Comment',
    category: 'Classification',
    type: 'string',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp6',
    name: 'Width',
    field: 'width',
    visible: true,
    header: 'Width',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp7',
    name: 'Height',
    field: 'height',
    visible: true,
    header: 'Height',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp8',
    name: 'Thickness',
    field: 'thickness',
    visible: true,
    header: 'Thickness',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fp9',
    name: 'Area',
    field: 'area',
    visible: true,
    header: 'Area',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  }
]

export const fixedChildParameters: Parameter[] = [
  {
    id: 'fc1',
    name: 'Category',
    field: 'category',
    visible: true,
    header: 'Category',
    category: 'Classification',
    type: 'string',
    removable: false,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fc2',
    name: 'ID',
    field: 'id',
    visible: true,
    header: 'ID',
    category: 'Classification',
    type: 'string',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fc3',
    name: 'Mark',
    field: 'mark',
    visible: true,
    header: 'Mark',
    category: 'Classification',
    type: 'string',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fc4',
    name: 'Width',
    field: 'width',
    visible: true,
    header: 'Width',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fc5',
    name: 'Height',
    field: 'height',
    visible: true,
    header: 'Height',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  },
  {
    id: 'fc6',
    name: 'Length',
    field: 'length',
    visible: true,
    header: 'Length',
    category: 'Dimensions',
    type: 'number',
    removable: true,
    kind: 'bim',
    sourceValue: '',
    fetchedGroup: '',
    currentGroup: ''
  }
]
